puts "put your right arm out"
puts "put your left arm out"
puts "flip your right arm"
puts "flip your left arm"
puts "right arm, left shoulder"
puts "left arm, right shoulder"
puts "right arm behind head"
puts "left arm behind head"
puts "right arm, left hip"
puts "left arm, right hip"
puts "right arm, right hip"
puts "left arm, left hip"
puts "AYYYYY MACARENA! (turn)"